### ISSUE TITLE
文件丢失

### ISSUE THREAD

**Issue by Lu-jiang** [urkax/Maze-solver-using-reinforcement-learning#1]
您好，我没有看到您的可执行文件emmm
还是拒绝我这种小白呢wuuuu

**Comment by zaocan666** [comment]
抱歉，我白天去补一下------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;&quot;Lu-jiang&quot;<notifications@github.com&gt;
发送时间:&nbsp;2020年9月19日(星期六) 下午4:07
收件人:&nbsp;&quot;urkax/Maze-solver-using-reinforcement-learning&quot;<Maze-solver-using-reinforcement-learning@noreply.github.com&gt;;
抄送:&nbsp;&quot;Subscribed&quot;<subscribed@noreply.github.com&gt;;
主题:&nbsp;[urkax/Maze-solver-using-reinforcement-learning] 文件丢失 (#1)

**Comment by zaocan666** [comment]
已补充

**Comment by Lu-jiang** [comment]
一级棒！！
